language: java
deploy:
  provider: heroku
  api_key:
    secure: NsFBANedF1oj/mwCc1GhyGZ1nQXsAHLX8fwNLVy0ptOOdnkg/omK90KhDN7tLA8IVTwlQCq5DQ+FIj5dnDGrV554+oQDuxAdUGpMApOiKCA98JZqv+QVracfCrkarvthSMYnBM5Vum7jzPru/qr3qTI1V/V07QrKh4HQg0/hnS+AlYoxX3PRJHylBIL4gjXXckIiZ+d0bbLJ3ZLV7hFY+Qa7JscmUPCMhmlLS4DLB+YCK2h7oLaKOTKarkMow/qROK5UkOXn1/bChNPsHW4t4PgFhwYAbFBOMYQ0pc7OCsAh37LPOjAFe1St7rG72ZWsgFIEnNIxVFjVc8rL0mYa4V46L5UQ5bS13mpRaeHOJVlszwOEOUekUAnHZ4t7fkDQ/1hd0nq05rmf9nv9tRdckE4eIW8zT3SP55hEx3TvjHE4Ue7rAeoMq4visVUnxlfQ07i/Gw3I3J/UNxcddI4DBFEppeRKEGsLBBl+hhS86lI0WmfsPxjZ3X+Mh4RDaIhZMUkJOyKYvTEn58IV4vURtSdH7IPz8DbffZLxzUFa9kONqJB/6Kcuw8a3ooK0DmHr6wHHRmNiPSY5KoRhyOMef2aK28wN2hmUV8YqwGNMC5tjt0YEGbOdm5yvYuvdFFr1Sd4NBVzHdpNShI7PmET7t1OOwRltuzACUJ40y0BnQoY=
  app: lukuvinkkikirjasto
  on:
    repo: karoliinaemilia/Lukuvinkkikirjasto-miniprojekti
